<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TextForge.Core\TextForge.Core.csproj" />
    <ProjectReference Include="..\TextForge.Export\TextForge.Export.csproj" />
    <ProjectReference Include="..\TextForge.Modules\TextForge.Modules.csproj" />
    <ProjectReference Include="..\TextForge.Storage\TextForge.Storage.csproj" />
    <ProjectReference Include="..\TextForge.Versioning\TextForge.Versioning.csproj" />
  </ItemGroup>

</Project>
